name: room_repository
description: Dart package which manages the Hotel.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  uuid: ^4.4.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true