// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjD27TF8J6VYP8aOkqOzfWbawqnkJg_k',
    appId: '1:118280658959:web:98b5f877004b92cc83037a',
    messagingSenderId: '118280658959',
    projectId: 'hotelbookingver2-8208b',
    authDomain: 'hotelbookingver2-8208b.firebaseapp.com',
    storageBucket: 'hotelbookingver2-8208b.appspot.com',
    measurementId: 'G-FS6ESTBX6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ODw_biU7Kqr0FSrvl7_W1tjHaxnSoyw',
    appId: '1:118280658959:android:737b4066c4f71a1083037a',
    messagingSenderId: '118280658959',
    projectId: 'hotelbookingver2-8208b',
    storageBucket: 'hotelbookingver2-8208b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnOtXWFXuSGf21wMlZ75ZlVYOnEe4YMU',
    appId: '1:118280658959:ios:85fb5c752705187a83037a',
    messagingSenderId: '118280658959',
    projectId: 'hotelbookingver2-8208b',
    storageBucket: 'hotelbookingver2-8208b.appspot.com',
    iosBundleId: 'com.example.flutterHotelBookingVer2',
  );
}
